// Generated by ts-to-zod
import { z } from 'zod';
import { Stat, Unit } from './Profession';

export const targetSchema = z.object({
   all: z.array(z.string()).optional(),
   any: z.array(z.string()).optional(),
   recipes: z.array(z.number()).optional(),
});

export const statSchema = z.nativeEnum(Stat);

export const unitSchema = z.nativeEnum(Unit);

export const effectSchema = z.object({
   amount: z.number().optional(),
   stat: statSchema.optional(),
   unit: unitSchema.optional(),
   modifyslots: z.array(z.number()).optional(),
});

export const perkSchema = z.object({
   unlockRank: z.number(),
   isMajorPerk: z.boolean(),
   perkID: z.number(),
   description: z.string(),
   effects: z.array(effectSchema).optional(),
   target: targetSchema.optional(),
});

export const talentPathSchema = z.object({
   name: z.string(),
   pathDescription: z.string(),
   children: z.array(z.number()),
   target: targetSchema.optional(),
   effects: z.array(effectSchema).optional(),
   perkInfos: z.array(perkSchema),
   pathID: z.number(),
});

export const specialisationSchema = z.object({
   rootPathID: z.number(),
   name: z.string(),
   description: z.string(),
   paths: z.array(talentPathSchema),
});

export const professionSchema = z.object({
   name: z.string(),
   icon: z.string(),
   skillLineID: z.number(),
   specialisations: z.array(specialisationSchema),
});
