// Generated by ts-to-zod
import { z } from 'zod';

export const reagentSchema = z.object({
   quantity: z.number(),
   name: z.string(),
   id: z.number(),
});

export const modifiedSlotSchema = z.object({
   name: z.string(),
   id: z.number(),
});

export const recipeSchema = z.object({
   recipeID: z.number(),
   reagents: z.array(reagentSchema).optional(),
   modifiedSlots: z.array(modifiedSlotSchema).optional(),
});

export const itemSchema = z.object({
   type: z.string(),
   name: z.string(),
   id: z.number(),
   subclassID: z.number(),
   subType: z.string(),
   classID: z.number(),
   tradeSkillLineID: z.number(),
   wowCat: z.string(),
   inventoryType: z.string(),
   recipe: recipeSchema,
});
