// Generated by ts-to-zod
import { z } from 'zod';

export const realmSchema = z.object({
	name: z.string(),
	id: z.number(),
	slug: z.string()
});

export const userRecipeSchema = z.object({
	recipeID: z.number(),
	name: z.string()
});

export const characterProfessionSchema = z.object({
	name: z.string(),
	id: z.number(),
	recipes: z.array(userRecipeSchema)
});

export const characterSchema = z.object({
	professions: z.array(characterProfessionSchema).optional(),
	name: z.string(),
	id: z.number(),
	realm: realmSchema,
	faction: z.union([z.literal('HORDE'), z.literal('ALLIANCE')]),
	level: z.number()
});

export const userSchema = z.object({
	battleTag: z.string(),
	creationDate: z.date(),
	region: z.union([
		z.literal('eu'),
		z.literal('us'),
		z.literal('kr'),
		z.literal('tw'),
		z.literal('cn')
	]),
	characters: z.array(characterSchema)
});
